In [31]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
import os
os.listdir('/content/drive/MyDrive/')

['GRE-root-words-flashcards.pdf',
 'Classroom',
 'korean cerificate.pdf',
 'KETAN RESUME or cv.pdf',
 'bike insurance.pdf',
 'KOREAN CERTIFICATE 2.pdf',
 'RefundFormfilled (1).pdf',
 'RefundFormfilled.pdf',
 'i 20.pdf',
 'bank statement Ishan..pdf',
 'Bank.pdf',
 'i20 d.pdf',
 'Immunization..pdf',
 " 'Rent Agreement 2024-2025'.pdf",
 'AHP_ubreakifix_presentation.pptx',
 'HIPAA Compliance Agreement - 11 17 24, 11:23\u202fAM.pdf',
 'KIT Employment Contract - 11_17_24, 11_23\u202fAM.pdf',
 'KIT Employment Contract - 11 17 24, 11:23\u202fAM.pdf',
 'NDA K.I.T. - 11 17 24, 11:19\u202fAM.pdf',
 'KIT 24, 11:19\u202fAM.pdf',
 ' KIT ii 24, 11:23\u202fAM.pdf',
 'KIT iii24, 11:23\u202fAM.pdf',
 'KIT 24 iii 11:23\u202fAM.pdf',
 'dec bank statement.pdf',
 'shipping label.pdf',
 'pdf24_images_merged.pdf',
 '20250108_154507.jpg',
 'agreement.pdf',
 'beer manufacturing.pdf',
 'Population-Latin-and-Caribbean-Countries-2010-2019.xlsx',
 'Optional Practical Training Presentation - Spring 2025.pdf',
 'Offer Letter Fall23_Ishan.pdf',
 'I 765.pdf',
 'Colab Notebooks',
 'REGISTRAR_Forms_DiplomaMailingRequest_copy (1).pdf',
 'REGISTRAR_Forms_DiplomaMailingRequest_copy.pdf',
 'Inventory.csv',
 'Products.csv',
 'cover letter v.docx',
 'Ishan Chandra_Resume_1_(i).docx',
 "I am sharing 'Licence 21 Aug 25' with you.pdf",
 'Ishan_Chandra_Social.docx',
 'Ishan_Chandra_Social.pdf',
 'Ishan_Chandra_Management^L.docx',
 'portfolio.docx',
 'Ishan_Chandra_Resume_1__i__5 (1).docx',
 'Google Earth',
 'list of 10 companies not very knmown but still th... (1).gsheet',
 'list of 10 companies not very knmown but still th....gsheet',
 'in a separate window.gsheet',
 'New Training Course Launch Notification.gform',
 'Ishan_Chandra_Resume_1__i__5 (1)updated1.docx',
 'Linkedn job post .gsheet',
 'Linkedin Job Post.pptx',
 'lease_40_Romaine-2nd-2025-2026 new-2.pdf',
 'Enrollment_Form_Training and Consultancy (1).docx',
 'Payment Authorization Form (2).docx',
 'Payment Authorization Form (1).docx',
 'Enrollment_Form_Training and Consultancy.docx',
 'Screen Recording 2025-12-11 201206.mp4',
 'Invoice-BGLFROKL-0002.pdf',
 'Receipt-2597-2254-1.pdf',
 'Payment Authorization Form.docx',
 'lv_0_20260121030817.mp4',
 'Deep Work PDF_merged.pdf',
 'olist_customers_dataset.csv',
 'olist_order_reviews_dataset.csv',
 'olist_order_payments_dataset.csv',
 'olist_geolocation_dataset.csv',
 'olist_order_items_dataset.csv',
 'product_category_name_translation.csv',
 'olist_products_dataset.csv',
 'olist_sellers_dataset.csv',
 'olist_orders_dataset.csv']

In [33]:
import pandas as pd

orders = pd.read_csv('/content/drive/MyDrive/olist_orders_dataset.csv')
customers = pd.read_csv('/content/drive/MyDrive/olist_customers_dataset.csv')
reviews = pd.read_csv('/content/drive/MyDrive/olist_order_reviews_dataset.csv')

In [34]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [35]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
import pandas as pd

orders = pd.read_csv('/content/drive/MyDrive/olist_orders_dataset.csv')

orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])

orders['delivery_time'] = (
    orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']
).dt.days

In [38]:
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])
orders['is_late'] = orders['order_delivered_customer_date'] > orders['order_estimated_delivery_date']

In [39]:
import pandas as pd

orders = pd.read_csv('/content/drive/MyDrive/olist_orders_dataset.csv')
reviews = pd.read_csv('/content/drive/MyDrive/olist_order_reviews_dataset.csv')
customers = pd.read_csv('/content/drive/MyDrive/olist_customers_dataset.csv')

In [40]:
df = orders.merge(reviews, on='order_id')

In [41]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,359d03e676b3c069f62cadba8dd3f6e8,5,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,e50934924e227544ba8246aeb3770dd4,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51

In [42]:
import pandas as pd

customers = pd.read_csv('/content/drive/MyDrive/olist_customers_dataset.csv')

df = df.merge(customers, on='customer_id')

In [43]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,a54f0611adc9ed256b57ede6b6eb5114,4,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,8d5266042046a06655c8db133d120ba5,4,Muito boa a loja,Muito bom o produto.,2018-08-08 00:00:00,2018-08-08 18:37:50,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,e73b67b67587f7644d5bd1a52deb1b01,5,NaN,NaN,2018-08-18 00:00:00,2018-08-22 19:07:58,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,359d03e676b3c069f62cadba8dd3f6e8,5,NaN,O produto foi exatamente o que eu esperava e e...,2017-12-03 00:00:00,2017-12-05 19:21:58,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,e50934924e227544ba8246aeb3770dd4,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 13:02:51,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [58]:
df.groupby('is_late')['review_score'].mean()

is_late
False    4.214307
True     2.566550
Name: review_score, dtype: float64

In [51]:
display(df.columns)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'review_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp', 'customer_unique_id',
       'customer_zip_code_prefix', 'customer_city', 'customer_state'],
      dtype='object')

In [59]:
df.groupby('review_score')['delivery_time'].mean()

review_score
1    20.849825
2    16.194832
3    13.795278
4    11.848054
5    10.224097
Name: delivery_time, dtype: float64

In [60]:
df['is_late'].mean()

np.float64(0.0776122712247037)

In [48]:
df.groupby('customer_state')['review_score'].mean().sort_values()

customer_state
RR    3.608696
AL    3.751208
MA    3.764075
SE    3.808023
PA    3.849174
CE    3.851016
BA    3.860888
RJ    3.874971
PI    3.920570
PE    4.011543
PB    4.018832
ES    4.041667
GO    4.042490
AC    4.049383
RO    4.051587
DF    4.064711
SC    4.071764
TO    4.096774
MT    4.102990
RN    4.105809
MS    4.118785
RS    4.133321
MG    4.136172
SP    4.173951
PR    4.180032
AM    4.183673
AP    4.194030
Name: review_score, dtype: float64

In [46]:
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [45]:
df['review_score'].notnull().mean()

np.float64(1.0)

In [54]:
import pandas as pd

orders = pd.read_csv('/content/drive/MyDrive/olist_orders_dataset.csv')
customers = pd.read_csv('/content/drive/MyDrive/olist_customers_dataset.csv')
reviews = pd.read_csv('/content/drive/MyDrive/olist_order_reviews_dataset.csv')

df = orders.merge(reviews, on='order_id')
df = df.merge(customers, on='customer_id')

df['bad_review'] = df['review_score'].apply(lambda x: 1 if x <= 2 else 0)

In [55]:
import pandas as pd

orders = pd.read_csv('/content/drive/MyDrive/olist_orders_dataset.csv')
reviews = pd.read_csv('/content/drive/MyDrive/olist_order_reviews_dataset.csv')
customers = pd.read_csv('/content/drive/MyDrive/olist_customers_dataset.csv')

# Convert timestamp columns to datetime objects for calculation
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

# Calculate 'delivery_time' and 'is_late' columns on the orders DataFrame
orders['delivery_time'] = (
    orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']
).dt.days
orders['is_late'] = orders['order_delivered_customer_date'] > orders['order_estimated_delivery_date']

df = orders.merge(reviews, on='order_id')
df = df.merge(customers, on='customer_id')

df['bad_review'] = df['review_score'].apply(lambda x: 1 if x <= 2 else 0)

X = df[['delivery_time', 'is_late']].fillna(0)
y = df['bad_review']

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [64]:
y_pred = model.predict(x_test)
display(y_pred)

array([0, 0, 0, ..., 0, 0, 0])

In [65]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8883849836230788

In [66]:
model.feature_importances_

array([0.65366795, 0.34633205])